### ISSUE TITLE
Prepare library for first release

### ISSUE THREAD

**Issue by elisabethstenholm** [UniMath/SymmetryBookFormalization#195]
### TODO
- [ ] #714
- [ ] Clean up commented code
- [x] Clean up unused imports (?)
- [x] #479
- [x] Add symbol for coproducts
- [x] Syntax for Id (?)
- [x] Change name of src/README (?)
- [ ] Complete refactoring of synthetic homotopy theory
- [ ] Make sure all files conform to guidelines

**Comment by EgbertRijke** [comment]
Some more suggestions for a release:
- Write documentation
- Write an article presenting the library

**Comment by EgbertRijke** [comment]
website version that corresponds statically to the release (suggested by Leo)

**Comment by elisabethbonnevier** [comment]
Do we want to keep or remove src/labels.lagda.md?

**Comment by EgbertRijke** [comment]
Yes

**Comment by fredrik-bakke** [comment]
Item 3 is resolved by #502, which adds the simplistic script `scripts/remove_unused_imports.py` that finds and removes unused imports. However, this script is not automatic, (it's a bit hacky and takes quite a long time to complete, e.g. 6.4 hours on my Mac for that PR) thus it will have to be occasionally rerun.

**Comment by fredrik-bakke** [comment]
Regarding items 1 and 2, it would be possible (and not very hard) to ban comments and holes with a pre-commit script. Additionally, we could ban `--allow-unsolved-metas`.
